
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: musicdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
